### ISSUE TITLE
multistream_app to much cpu usage

### ISSUE THREAD

**Issue by MyraBaba** [hailo-ai/Hailo-Application-Code-Examples#146]
Hi,

We are testing multistream_app and compiled it succesfully. 

we tested with 5 2Mp sources and its almost using all cpu our i9 server. is this normal ? 

<img width="1085" alt="Screen Shot 2023-10-18 at 23 32 09" src="https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/17505439/803339a1-4492-4b2d-97ba-cd3a7e498653">

**Comment by MyraBaba** [comment]
is decoding take such cpu ?  how we can enable vaapi ?

Best

**Comment by MyraBaba** [comment]
can we use for face detection / retinaface ? I changed the cpp file accordingly for retina face but its just printing : 


APP_RUNTIME_DIR: /local/shared_with_docker/Hailo-Application-Code-Examples/runtime/gstreamer/multistream_app/

not running inference

**Comment by giladnah** [comment]
Hi @MyraBaba thanks you for your input.
This application besides implementing a multistream pipeline also introducing a more complicated source the "srcBin".
This source is build to demonstrate more complicated event handling like:

1. Handling camera, file, network URI with the same element.
2. Rewinding a video file to run it in a loop.
3. Handling RTSP disconnect events.

This code is "heavier" than a simple source and use more resources. It is not fined tuned and there probably lots of areas it can be upgraded.
If you do not need these extra features you can just use a regular src pipeline.
Please let me know what your needs are so I can help.

Regarding VAAPI. The SrcBin is using uridecode and decodebin. These are auto pluggers it means they will select the "best" available element to implement the task required. So if you have VAAPI installed they should automagically select the VAAPI decoder and post process.
To install VAAPI follow these instructions in the TAPPAS documentation - [GStreamer based x86 applications](https://github.com/hailo-ai/tappas/tree/master/apps/h8/gstreamer/x86_hw_accelerated)

After installation you can check which elements were used by adding the --dump-dot-files to the application run.
This will dump a dot file you can review pipeline_paused.dot and pipeline_playing.dot.
You can watch them using 'dot pipeline_playing.dot -Tx11' for example.

See more debug tool on [Debuging](https://github.com/hailo-ai/tappas/blob/ba00fd3a305ff8e333c624cf1391c4e33ac73432/docs/write_your_own_application/debugging.rst#debugging) 

Regarding the last question you should be able to replace the network, make sure you replace HEF and postprocess functions.
See the README file to see how to compile in DEBUG mode. You'll be able to add breakpoints to better understand the problem.

Please note that if you are running a newer TAPPAS version than hailo_sw_suite_2023-04 the roundrobin patch is not required as it is already merged.

Please share details on what you are trying to achieve and which version of TAPPAS you are using.
Good luck!
