### ISSUE TITLE
Do not hardcode number of classes being 80

### ISSUE THREAD

**Issue by Tsardoz** [hailo-ai/Hailo-Application-Code-Examples#167]
In runtime/python/yolo_general_inference/yolo_inference.py throughout 80 classes are hardcoded in throughout despite the number of classes being available from the command line.

**Comment by omerwer** [comment]
Hi @Tsardoz,
You are correct. It was overlooked while loading the script. It is now fix to be with the number of classes defined by the user (or defaults to 80 if no specification is given). 

Regards,
