### ISSUE TITLE
Can you give a multi-camera inference pipeline?

### ISSUE THREAD

**Issue by lswgh** [hailo-ai/Hailo-Application-Code-Examples#17]

**Comment by lswgh** [comment]
Is there a member like TensorRT IExecutionContext that can be use for multi-camera inference in hailort?

**Comment by omerwer** [comment]
@lswgh 
Hi,
Basically, the RE-ID example uses multiple files, that can be converted to multiple camera pipeline.
You can also see the examples we have in TAPPAS:
https://github.com/hailo-ai/tappas/tree/master/apps/h8/gstreamer/general
All those with the headline multi camera or multistream work with multiple cameras.

Regards,
