### ISSUE TITLE
'PcieDevice is deprecated'

### ISSUE THREAD

**Issue by Nand7773** [hailo-ai/Hailo-Application-Code-Examples#170]
When i tried to run sample application im getting this error. I just run 'PcieDevice()' after importing 'hailo_platform' on hailo python venv and the log result is-
>>> PcieDevice()
HailoHWObject is deprecated! Please use VDevice/Device object.
PcieDevice is deprecated! Please use VDevice/Device object.
PcieHcpControl is deprecated! Please Use Control object
<hailo_platform.pyhailort.hw_object.PcieDevice object at 0x7fe46afbb4c0>

**Comment by omerwer** [comment]
Hi @Nand7773 ,
What example is this?

**Comment by omerwer** [comment]
Hi @Nand7773 
All Python example are now update to work with the latest HailoRT release (v4.15.0). 
There should be no warning now.

Regards,
