### ISSUE TITLE
custom hef model

### ISSUE THREAD

**Issue by pahmduy** [hailo-ai/Hailo-Application-Code-Examples#187]
i'ed compiled an onnx yolov5m model to hef, that model is retrained by my own data for letter recognize
output from compile screen
[info] input_layer1: Pass
[info] conv3: Pass
[info] conv5: Pass
[info] normalization1: Pass
[info] conv7: Pass
[info] space_to_depth1: Pass
[info] conv12: Pass
[info] conv26: Pass
[info] batch_norm1_dc: Pass
[info] context_0_to_context_1_context_2_0: Pass
[info] auto_reshape_from_input_layer1_to_normalization1: Pass
[info] ew_add3: Pass
[info] ew_add8: Pass
[info] conv2_sd0: Pass
[info] conv20: Pass
[info] shortcut_from_conv1_to_conv2_sd0-3: Pass
[info] conv11_sd1: Pass
[info] conv10: Pass
[info] conv11_sd0: Pass
[info] conv8_sd1: Pass
[info] conv2_sd3: Pass
[info] ew_add5: Pass
[info] conv19_dc: Pass
[info] batch_norm1_d1: Pass
[info] conv23_d0: Pass
[info] concat2: Pass
[info] conv24: Pass
[info] conv21_d1: Pass
[info] conv2_sdc: Pass
[info] ew_add2: Pass
[info] concat_from_conv2_sd0-3_to_conv2_sdc: Pass
[info] conv1_sd0: Pass
[info] conv25_dc: Pass
[info] conv17_d0: Pass
[info] smuffers_shortcut_conv7_to_conv8: Pass
[info] conv27: Pass
[info] conv23_d1: Pass
[info] conv13: Pass
[info] conv11_sd3: Pass
[info] conv19_d1: Pass
[info] conv16: Pass
[info] conv22: Pass
[info] conv2_sd1: Pass
[info] conv15_dc: Pass
[info] conv17_dc: Pass
[info] conv18: Pass
[info] ew_add6: Pass
[info] conv23_dc: Pass
[info] conv2_sd2: Pass
[info] batch_norm1_d0: Pass
[info] smuffers_shortcut_conv5_to_conv6: Pass
[info] ew_add4: Pass
[info] conv9: Pass
[info] conv19_d0: Pass
[info] conv11_sdc: Pass
[info] batch_norm1_fs: Pass
[info] conv25_d0: Pass
[info] conv8_sd0: Pass
[info] concat1: Pass
[info] conv14: Pass
[info] conv21_dc: Pass
[info] conv2_sd4: Pass
[info] conv4: Pass
[info] conv1_sd2: Pass
[info] conv1_sd1: Pass
[info] conv15_d1: Pass
[info] conv6_sd0: Pass
[info] batch_norm2: Pass
[info] conv25_d1: Pass
[info] conv1_sdc: Pass
[info] conv21_d0: Pass
[info] conv11_sd2: Pass
[info] conv15_d0: Pass
[info] conv17_d1: Pass
[info] conv8_sdc: Pass
[info] ew_add1: Pass
[info] ew_add7: Pass
[info] conv6_sdc: Pass
[info] conv6_sd1: Pass
[info] ew_add12: Pass
[info] conv33: Pass
[info] conv31: Pass
[info] conv29: Pass
[info] context_1_to_context_2_5: Pass
[info] conv34_dc: Pass
[info] context_1_to_context_2_7: Pass
[info] concat_from_conv45_d0-2_to_conv45_dc: Pass
[info] concat_from_conv46_d3-5_to_conv46_dc: Pass
[info] conv46_d2: Pass
[info] conv36_d0: Pass
[info] conv49: Pass
[info] conv28_d3: Pass
[info] conv51: Pass
[info] conv35: Pass
[info] conv36_dc: Pass
[info] conv42_d0: Pass
[info] conv34_d0: Pass
[info] shortcut_from_shortcut_from_conv44_to_conv45_d0-3_to_conv45_d0-2: Pass
[info] conv32_d1: Pass
[info] conv39: Pass
[info] shortcut_from_conv44_to_conv45_d0-3: Pass
[info] conv46_dc: Pass
[info] conv47: Pass
[info] conv52_dc: Pass
[info] conv48: Pass
[info] conv52_d0: Pass
[info] concat_from_conv45_d0-1_to_concat_from_conv45_d0-2_to_conv45_dc: Pass
[info] conv50_dc: Pass
[info] conv44: Pass
[info] context_0_to_context_1_in_1: Pass
[info] conv32_d0: Pass
[info] conv46_d3: Pass
[info] conv45_d3: Pass
[info] conv40_d1: Pass
[info] shortcut_from_conv27_to_conv28_d0-3: Pass
[info] conv45_d1: Pass
[info] conv38_d1: Pass
[info] conv32_dc: Pass
[info] concat_from_conv28_d3-5_to_conv28_dc: Pass
[info] conv46_d5: Pass
[info] concat_from_conv46_d0-2_to_conv46_dc: Pass
[info] conv46_d1: Pass
[info] conv45_d0: Pass
[info] conv42_d1: Pass
[info] conv30: Pass
[info] ew_add13: Pass
[info] ew_add11: Pass
[info] conv50_d1: Pass
[info] conv34_d1: Pass
[info] conv40_dc: Pass
[info] conv28_d4: Pass
[info] conv36_d1: Pass
[info] conv41: Pass
[info] conv38_d0: Pass
[info] conv43: Pass
[info] ew_add14: Pass
[info] conv45_dc: Pass
[info] conv52_d1: Pass
[info] conv28_d5: Pass
[info] concat_from_conv28_d0-2_to_conv28_dc: Pass
[info] conv38_dc: Pass
[info] context_1_to_context_2_9: Pass
[info] conv28_d1: Pass
[info] conv42_dc: Pass
[info] conv45_d2: Pass
[info] ew_add10: Pass
[info] batch_norm3: Pass
[info] shortcut_from_conv45_to_conv46_d0-3: Pass
[info] conv46_d4: Pass
[info] conv28_dc: Pass
[info] conv37: Pass
[info] conv28_d0: Pass
[info] concat3: Pass
[info] conv50_d0: Pass
[info] shortcut_from_shortcut_from_conv45_to_conv46_d0-3_to_conv46_d0-2: Pass
[info] conv28_d2: Pass
[info] ew_add9: Pass
[info] conv40_d0: Pass
[info] conv53: Pass
[info] conv46_d0: Pass
[info] output_layer2: Pass
[info] output_layer1: Pass
[info] output_layer3: Pass
[info] batch_norm4: Pass
[info] concat4: Pass
[info] conv55: Pass
[info] resize2: Pass
[info] conv54: Pass
[info] conv74: Pass
[info] context_1_to_context_2_in_10: Pass
[info] context_1_to_context_2_in_8: Pass
[info] conv58: Pass
[info] conv78_dc: Pass
[info] auto_reshape_from_conv93_to_output_layer3: Pass
[info] conv59_d1: Pass
[info] context_1_to_context_2_in_6: Pass
[info] conv93: Pass
[info] conv61_dc: Pass
[info] auto_reshape_from_conv74_to_output_layer1: Pass
[info] conv59_dc: Pass
[info] conv80_d0: Pass
[info] conv67: Pass
[info] context_0_to_context_2_in_4: Pass
[info] conv71: Pass
[info] conv79: Pass
[info] conv59_d0: Pass
[info] conv69: Pass
[info] conv86: Pass
[info] resize1: Pass
[info] conv77: Pass
[info] concat9: Pass
[info] conv56: Pass
[info] concat7: Pass
[info] concat6: Pass
[info] conv80_d1: Pass
[info] conv70_d1: Pass
[info] conv82: Pass
[info] conv83_d1: Pass
[info] batch_norm7: Pass
[info] conv91: Pass
[info] conv81: Pass
[info] conv66: Pass
[info] conv73_sd0: Pass
[info] conv84: Pass
[info] conv62: Pass
[info] conv61_d1: Pass
[info] conv63: Pass
[info] conv92: Pass
[info] conv64: Pass
[info] conv73_sdc: Pass
[info] conv87: Pass
[info] conv78_d0: Pass
[info] conv90_d1: Pass
[info] conv78_d1: Pass
[info] concat8: Pass
[info] concat10: Pass
[info] conv88_d1: Pass
[info] conv89: Pass
[info] conv90_d0: Pass
[info] conv65: Pass
[info] batch_norm8: Pass
[info] conv80_dc: Pass
[info] conv83_d0: Pass
[info] conv75: Pass
[info] conv72: Pass
[info] concat12: Pass
[info] conv76: Pass
[info] conv61_d0: Pass
[info] conv85: Pass
[info] batch_norm5: Pass
[info] concat11: Pass
[info] conv90_dc: Pass
[info] conv70_dc: Pass
[info] conv68_d0: Pass
[info] conv68_dc: Pass
[info] batch_norm6: Pass
[info] conv88_d0: Pass
[info] conv88_dc: Pass
[info] conv68_d1: Pass
[info] conv83_dc: Pass
[info] auto_reshape_from_conv84_to_output_layer2: Pass
[info] conv73_sd1: Pass
[info] conv70_d0: Pass
[info] concat5: Pass
[info] conv60: Pass
[info] conv57: Pass
[info] Solving the allocation (Mapping), time per context: 59m 59s
Model Details
--------------------------------  -----------
Input Tensors Shapes              640x640x3
Operations per Input Tensor       52.24 GOPs
Operations per Input Tensor       26.17 GMACs
Pure Operations per Input Tensor  52.24 GOPs
Pure Operations per Input Tensor  26.17 GMACs
Model Parameters                  23.52 M
--------------------------------  -----------

but run with yolov5_yolov7_detection example i get error
[HailoRT] [error] CHECK failed - Got HAILO_TIMEOUT while waiting for descriptors in write_buffer (channel_id=0:2)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_TIMEOUT(4)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_TIMEOUT(4) - HwWriteElement1_yolov5m/input_layer1 (H2D) failed with status=HAILO_TIMEOUT(4)
[HailoRT] [error] CHECK failed - Got HAILO_TIMEOUT while waiting for descriptors in write_buffer (channel_id=0:2)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_TIMEOUT(4)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_TIMEOUT(4) - HwWriteElement1_yolov5m/input_layer1 (H2D) failed with status=HAILO_TIMEOUT(4)
[HailoRT] [error] CHECK failed - Got HAILO_TIMEOUT while waiting for descriptors in write_buffer (channel_id=0:2)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_TIMEOUT(4)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_TIMEOUT(4) - HwWriteElement1_yolov5m/input_layer1 (H2D) failed with status=HAILO_TIMEOUT(4)

i can run with model provide by hailo successfull
please help me to solve this problem

**Comment by omerwer** [comment]
Hi @pahmduy,
It seems that the problem is that the writing thread gets an exception for some reason, but it can be because of the HEF, image or video supplied.
It's difficult to know with these details what is the problem. Please contact me via email at omerw@hailo.ai and I'll try to help you figure out the problem.
