### ISSUE TITLE
Query: Is there any way to use hailo_scheduler with raw streams?

### ISSUE THREAD

**Issue by almex-m-bulbul** [hailo-ai/Hailo-Application-Code-Examples#189]
As per my understanding, hailo provides two types of API:
 1.  **Raw Streams** : which allows low level interactions with the device and supports async read, write.
 2. **Virtual Streams** : Provide high level interface that is used to interact with the device. Supports _HAILO_SCHEDULER_.
 
Unfortunately I couldn't find anything about **async read/write with HAILO_SCHEDULER**

 I have gone through all of the sample code provided in [Hailo-Application-Code-Examples](https://github.com/hailo-ai/Hailo-Application-Code-Examples/tree/main) and example code in [hailort](https://github.com/hailo-ai/hailort/tree/master/hailort/libhailort/examples) branch. Also checked the HailoRt user guide: Release 4.15.0.  
 
 Is it possible to use raw streams async read/write with HAILO_SCHEDULER?

**Comment by omerwer** [comment]
Hi @almex-m-bulbul,
According to the internal changelog I looked at, the async API supports running with the Scheduler in HailoRT v4.15.0.
In the upcoming release (v4.16.0, start of 2024), an async vstream API supposed to be released and both (raw streams and vstreams async API) will support running with the Scheduler. 
Regards,
