### ISSUE TITLE
post_processing  undefined reference

### ISSUE THREAD

**Issue by MyraBaba** [hailo-ai/Hailo-Application-Code-Examples#2]
Hi,
@erangur 
I try to compile in the Hailo_sw_suite env and has below error:

Ubuntu Release:	18.04

`(hailo_venv) alp2080@alp2080:/data/hailo/hailo_sw_suite/yolov5_v7_det$ ./build.sh
-I- Building x86_64
-- Found OpenCV: /usr/local/include/opencv4
-- Configuring done
-- Generating done
-- Build files have been written to: /data/hailo/hailo_sw_suite/yolov5_v7_det/build/x86_64
[ 50%] Linking CXX executable vstream_yolov7_example_cpp
/usr/bin/ld: CMakeFiles/vstream_yolov7_example_cpp.dir/yolov5_yolov7_inference.cpp.o: in function `post_processing_all(std::vector<std::shared_ptr<FeatureData>, std::allocator<std::shared_ptr<FeatureData> > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::chrono::duration<double, std::ratio<1l, 1l> >&)':
/data/hailo/hailo_sw_suite/yolov5_v7_det/yolov5_yolov7_inference.cpp:84: undefined reference to `post_processing(unsigned char*, float, float, unsigned char*, float, float, unsigned char*, float, float)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/vstream_yolov7_example_cpp.dir/build.make:148: vstream_yolov7_example_cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/vstream_yolov7_example_cpp.dir/all] Error 2
make: *** [Makefile:84: all] Error 2`

**Comment by omerwer** [comment]
Hi @MyraBaba 
One of the includes in yolo_post_processing.cpp was wrong. I fixed it, and it should work now.

Regards,

**Comment by MyraBaba** [comment]
Hi,

Now its compiled. Testing


Best

BC

**Comment by MyraBaba** [comment]
Hi,

It ran for a while and produce the :


Detection: bus, Confidence: 44.26%
Detection: bus, Confidence: 33.13%
Detection: car, Confidence: 31.80%
Detection: truck, Confidence: 23.74%
Detection: car, Confidence: 21.15%
Detection: car, Confidence: 18.62%
[HailoRT] [error] CHECK_AS_EXPECTED failed - UserBufferQueueElement_post_infer14_yolov5m_wo_spp_60p/conv74 (D2H) failed with status=HAILO_TIMEOUT(4) (timeout=10000ms)
Failed reading with status = 4
[HailoRT] [error] CHECK_AS_EXPECTED failed - UserBufferQueueElement_post_infer13_yolov5m_wo_spp_60p/conv84 (D2H) failed with status=HAILO_TIMEOUT(4) (timeout=10000ms)
Failed reading with status = 4
[HailoRT] [error] CHECK_AS_EXPECTED failed - UserBufferQueueElement_post_infer12_yolov5m_wo_spp_60p/conv93 (D2H) failed with status=HAILO_TIMEOUT(4) (timeout=10000ms)
Failed reading with status = 4
Read failed with status 4
Failed running inference with status = 4

**Comment by MyraBaba** [comment]
@omerwer 

The resulting box looks for 640x640 downsized frame. How we can get normalized coordinates that we can correctly use on the original frame to draw boxes ? 

Best

**Comment by omerwer** [comment]
@MyraBaba 
1. The VideoWriter was indeed not working properly. I adjusted the code and from my tests it now run fine.
2. About the timeout you get - I can't reproduce. On which platform and CPU\GPU are you running it on?
3. In the current version I get tight bounding boxes with the yolov5m_wo_spp.hef. Indeed, the detections are made on a 640x640 images.

Does this answer your questions?

**Comment by MyraBaba** [comment]
Thanks ,

3 . We run it successfully at  larger resolution and the system resizing it to the 640x640 which is network size.
     How we can get the normalized box as in the tappas ? So we can draw boxes on the original video 

1. Will test VideoWriter thanks.



For time out I will collect more debug info and send you for your records 

Best

**Comment by omerwer** [comment]
@MyraBaba 
To scale the bounding boxes, you basically need to eliminate the effect of the input resolution of the network, and apply the relevant scaling of your image.
So, if the network input resolution is 640x640 and your image is HxW, then to scale the X coordinates - X / 640 * W, and to scale the Y coordinates - Y / 640 * H.
As per you question, I updated the code to apply the detection on the video resolution. On my machine the boxes where tight for the yolov5m network.

Regards,

**Comment by omerwer** [comment]
@MyraBaba 
There shouldn't be any difference in accuracy between TAPPAS detection.sh and native examples. The metric used to measure the accuracy is mAP, and is the same for both example. 
The video input is different, which can cause it to look less accurate, and also the way we apply postprocess is different because of the different framework, but the bounding boxes that result from the inference are the same.

The way chosen to draw the bounding box is the user's choice. Specifically here the work effort to do it is not large.

About the IDE for TAPPAS - it's a matter of self comfort. Some people use vim, some VSCode and some other IDEs.   

Regards,

**Comment by MyraBaba** [comment]
Thank you for the information.

The uncomforting thing is the debugging in the tappas. This is why I asked the ide for debugging possibility in IDe for tappas postprocess / elements.

Best
