### ISSUE TITLE
yolov5_postprocess_python

### ISSUE THREAD

**Issue by chenhongming** [hailo-ai/Hailo-Application-Code-Examples#231]
My hailo8 chip is installed on an aarch64 edge device, and the system is ubuntu20.04. So I can’t use hailo_model_zoo’s YoloPostProc?

from hailo_model_zoo.core.postprocessing.detection.yolo import YoloPostProc

![捕获3](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/29920966/25eef0a6-efdc-462a-8d44-28dfa280a293)

Looking forward to your reply

**Comment by nadaved1** [comment]
Hi @chenhongming, The model-zoo was not tested on an aarch system, but you can download the source code from the git and compile on your system.
https://github.com/hailo-ai/hailo_model_zoo
