### ISSUE TITLE
Inference Issues with Converted Models on Windows - No Detection on my own model.

### ISSUE THREAD

**Issue by pcycccccc** [hailo-ai/Hailo-Application-Code-Examples#248]
Recently, I have been attempting to perform image inference on Windows using models that I have converted myself. To verify the feasibility of my conversion method, I tested three models: person_v8n.onnx (from my own dataset with only a "person" category), yolov8n.onnx (converted from a pt model provided by the official ultralytics project), and yolov8n_hailo.onnx (a model provided by the official hailo_mz). Following the instructions from the model_zoo, I used the same commands to convert the onnx models into hef models. Notably, person_v8n.onnx differs from the other two models in that it contains only one category, whereas both yolov8n.onnx and yolov8n_hailo.onnx encompass 80 categories. The calibration dataset for person_v8n.onnx consists of images from specific scenes, while the datasets for yolov8n.onnx and yolov8n_hailo.onnx are from coco_val2017. All three models were successfully converted to hef models, and I have integrated the NMS into the model files using yolov8n_nms_config.json. However, during testing, I observed that while yolov8n.hef and yolov8n_hailo.hef were able to display bounding boxes on the images, person_v8n.hef seemed to detect no targets as no bounding boxes were drawn on the images (no other errors occurred during the process, and the categories and vstream_output_data were modified according to the model specifications). Could anyone advise on potential reasons for this issue?
![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/108455796/d60413c7-c82c-4d2e-bb0f-901979dc8b27)
![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/108455796/b3ccc097-f0bb-4855-acc9-4e135362c1ae)
![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/108455796/e14bf8ed-383f-4e9e-bf4d-23db3d017db6)
![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/108455796/91b36b8f-fe48-4f11-a8fe-a4335e0dd920)

![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/108455796/bbc5b244-5b8a-4c00-b9b7-fe3e8e9ac391)

After running the code，There are no objects on the image... so Sad!

**Comment by omerwer** [comment]
Hi @pcycccccc,
Since the example works for two other models, then the code itself is working properly, which means one of two things (or both):
1. The accuracy of your custom model is lower then that of the other models and there for doesn't surpass the score or IoU thresholds,
2. The models that work are trained to include "background" class while your model doesn't.

Since changing the scores & NMS threshold requires re-optimizing and re-compiling the model, I suggest that first try to check if your model includes a background class or not and adjust it\the code accordingly.

If that is not the case, try to lower the score threshold to 0.001 and keep IoU threshold to 0.7. If that doesn't work, try lowering the IoU threshold also.

Regards,

**Comment by pcycccccc** [comment]
Hi @omerwer ，
Thank you very much for your attention. I do not quite understand the significance of the 'background' category. I have tried adding or removing it, but this does not seem to affect my results, as I still cannot obtain any bounding boxes on the images. I have tried lowering the Score threshold to 0.001 and the IoU threshold to 0.45, and experimented with different threshold parameters to convert the model , but I am still unable to display any targets. 
![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/108455796/7f370533-2003-4c6f-a5bf-c091b1ffc136)
![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/108455796/1e6b7074-6535-46ef-bfd2-f8215e719216)

I am not entirely sure if I need to modify other parameters related to categories during the model conversion process. I only changed the model's path and the total number of categories, using the command to convert the model: hailomz compile --ckpt /root/autodl-tmp/my_data/person_v8n.onnx --calib-path /root/autodl-tmp/my_data/person_image/ --yaml /root/autodl-tmp/hailo_mz/hailo_model_zoo/hailo_model_zoo/cfg/networks/yolov8n.yaml --classes 1.

Below is the output content during the conversion process of my model.
![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/108455796/e23a1821-6c57-42f9-8756-df13a30e9c90)
![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/108455796/111b6db6-1b06-443c-80d4-943c71214990)
![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/108455796/b2e09b57-5443-49e4-93e0-01f0a63c9844)
![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/108455796/711c4935-0e71-46ad-90d2-b725bf18cdce)

It is worth noting that when I perform inference on the same image using person_v8.onnx (using onnxruntime for inference), it can output results normally with a Score threshold of 0.25 and an IoU threshold of 0.7.

I still cannot pinpoint the issue. From my perspective, model conversion and inference work normally for models with 80 classes, but inference using my own model does not yield the expected results.
