### ISSUE TITLE
Is there any solution c++ inference for 15h with /dev/video0 input?

### ISSUE THREAD

**Issue by HirosiUko** [hailo-ai/Hailo-Application-Code-Examples#249]
Hi, I am investigating with Hailo-15H.
I want to do inference of the image that is inputed by /dev/video0 in 15h device.
I have tested it with 'runtime/cpp/detection/yolov8_cross_compilation_h15' code. but it did not work.
Is there any solution to inference the image that is inputed by /dev/video0 in 15h device?

```
root@hailo15:~/ws/Test_v1/resources# ./yolov8_cross_compilation_h15 -input=/dev/video0 -hef=hefs/h15/yolov8s_h15.hef
-I-----------------------------------------------
-I-  Network  Name                                     
-I-----------------------------------------------
-I-  IN:  yolov8s/input_layer1
-I-----------------------------------------------
-I-  OUT: yolov8s/conv41
-I-  OUT: yolov8s/conv42
-I-  OUT: yolov8s/conv52
-I-  OUT: yolov8s/conv53
-I-  OUT: yolov8s/conv62
-I-  OUT: yolov8s/conv63
-I-----------------------------------------------

[ WARN:0@0.351] global /usr/src/debug/opencv/4.5.5-r0/git/modules/videoio/src/cap_gstreamer.cpp (2401) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Could not read from resource.
[ WARN:0@0.352] global /usr/src/debug/opencv/4.5.5-r0/git/modules/videoio/src/cap_gstreamer.cpp (1356) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@0.352] global /usr/src/debug/opencv/4.5.5-r0/git/modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
terminate called after throwing an instance of 'char const*'
Aborted
root@hailo15:~/ws/Test_v1/resources# 

```
The model that i would like to inference is yolov8m object detection.
Thanks,

**Comment by omerwer** [comment]
Hi @HirosiUko,
Support for camera input It is not yet implemented for this specific example, and we will work in that in the near future. But, I believe that if you take the yolov8_inference.cpp from the x86 yolov8 example:
https://github.com/hailo-ai/Hailo-Application-Code-Examples/blob/main/runtime/cpp/detection/yolov8/x86_64/yolov8_inference.cpp

It should work with the cross-compilation CMakeLists.txt here.

Regards,

**Comment by omerwer** [comment]
Hi @HirosiUko,

I just added the support that exists in the x86 yolov8 example for camera input. I have crossed-compiled the example successfully.
Please let me know if there's any issue with the example.

Regards,

**Comment by HirosiUko** [comment]
Hi @omerwer ,

Thank for your support.
Unfortunately, Even update your commit, it is not available to work using the camera input (as '/dev/video0') in Hailo-15h board.

I attached the log. Please review it and please help.

Log:
```shell
root@hailo15:~/ws/hailo_sample# ./yolov8_cross_compilation_h15_hailo_sample -hef=resources/hefs/h15/yolov8s_h15.hef -input=/dev/video0 -num=1
-I-----------------------------------------------
-I-  Network  Name                                     
-I-----------------------------------------------
-I-  IN:  yolov8s/input_layer1
-I-----------------------------------------------
-I-  OUT: yolov8s/conv41
-I-  OUT: yolov8s/conv42
-I-  OUT: yolov8s/conv52
-I-  OUT: yolov8s/conv53
-I-  OUT: yolov8s/conv62
-I-  OUT: yolov8s/conv63
-I-----------------------------------------------

[ WARN:0@0.347] global /usr/src/debug/opencv/4.5.5-r0/git/modules/videoio/src/cap_gstreamer.cpp (2401) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Could not read from resource.
[ WARN:0@0.348] global /usr/src/debug/opencv/4.5.5-r0/git/modules/videoio/src/cap_gstreamer.cpp (1356) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@0.348] global /usr/src/debug/opencv/4.5.5-r0/git/modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
terminate called after throwing an instance of 'char const*'
Aborted
root@hailo15:~/ws/hailo_sample# 
``` 
I am working on the meta-hailo-soc 1.2.2 SW base.
(https://github.com/hailo-ai/meta-hailo-soc/commit/7e82fbcf4b0e2800ded674fc66ff278fe8f570b4)

**Comment by HirosiUko** [comment]
Hi @omerwer ,
Thank for your support.
It works the camera input is available now.
I have 1 more question.
Is there any simple solution to translate the camera input stream format from NV12 to RGB(NHWC)?
The model compile (hef) with applying NV12 is so difficult.

**Comment by omerwer** [comment]
Hi @HirosiUko,
You have the option in Hailo to have the format change on your HEF by adding these commands in the model script you use to run optimization on the model:
```
yuv_to_rgb_layer = input_conversion(input_layer1, yuv_to_rgb, emulator_support=True)
nv12_to_yuv_layer = input_conversion(input_layer1, nv12_to_hailo_yuv, emulator_support=True)
```

You can have the Hailo device do the format conversion. 
There's no other way unfortunately to have the format conversion using Hailo. You can also use OpenCV option for the conversion:

```
void nv12ToRGB(const uchar* nv12Data, int width, int height, Mat& rgbFrame) {
    Mat yuvFrame(height + height / 2, width, CV_8UC1, (uchar*)nv12Data);

    // Convert NV12 to BGR
    cvtColor(yuvFrame, rgbFrame, COLOR_YUV2BGR_NV12);
} 
```

Please notice that if you choose to add the model script commands, the calibration data should also be in nv12 format.

Regards,

**Comment by HirosiUko** [comment]
Hi @omerwer ,
I tested with your second guide (use OpenCV option).
Here is my test code.
```
// yolov8_inference.cpp Line 344
cv::VideoCapture capture;
    size_t frame_count;
    if (input_path.empty()) {
        capture.open(0, cv::CAP_ANY);
        if (!capture.isOpened()) {
            throw "Error in camera input";
        }
        frame_count = -1;
        cv::Mat img;
        capture >> img;

        cv::imwrite("write_test1.jpg", img);
        std::cout << "Writing test image to write_test1.jpg done\n";
        nv12ToRGB(img.data, img.cols, img.rows, img);
        cv::imwrite("write_test2.jpg", img);
        std::cout << "Writing test image to write_test2.jpg done\n";
    }
```
Here is the result. 
The function `nv12ToRGB()` looks does not working correctly.

write_test1.jpg
![write_test1](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/53636578/0f5a5143-1886-4336-a23d-b28325ecc746)
write_test2.jpg
![write_test2](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/53636578/8aa6cc67-f209-4c75-8581-bbdc1b953f95)

If my test code was wrong, please let me know.
Thanks

**Comment by omerwer** [comment]
Hi @HirosiUko,
I see. I believe that it just a matter of implementation (maybe the format type should be CV_8UC3 and not CV_8UC1, or the cv::Mat should be initialized differently).
I'm not sure what the nature of the issue is exactly, If you want specific support for your issue, please open a ticket using the Hailo website with your request and we will assign this task to one of our engineers in the formal pipeline.

Regards,

**Comment by HirosiUko** [comment]
The above problem was caused by a memory leak in my code.
I will close this ticket.

**Comment by danny007-97** [comment]
Hello @HirosiUko ,

Would you be able to help me with code for Hailo-15 SBC Object detection code.
I wanted to take camera input and detect object and run this in continuous loop.
As I am quite new to the Hailo-15 board I am not able to understand the overall code structure so if you help me with base code for detection with camera input then it will accelerate my overall application developement.
Thank You.
