### ISSUE TITLE
fastsam result image?

### ISSUE THREAD

**Issue by dongxuanlb** [hailo-ai/Hailo-Application-Code-Examples#255]
Can you provide a rendering of the fastsam result? The post-processing effect I implemented myself is not as good as the official one.

**Comment by omerwer** [comment]
Hi @dongxuanlb,
Can you please elaborate exactly what is the problem you are experiencing and what is your request?

Regards,

**Comment by dongxuanlb** [comment]
Sorry for not describing the problem clearly.
What I need is: can you provide the image effect after the sample code is executed.


For example, for the yolov8 segmentation（c++)
this is the original image:
![dogs](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/865803/ad166de8-26b4-443c-8e27-a6f40325699b)
and this image is the post-processing effect I implemented myself:
![maskPrinted](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/865803/5cea2edc-4eaf-4dc2-b77c-0cef67fb799e)
This looks fine.

but，when I use [fastsam model ](https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/hefs/h8/fast_sam_s.hef)that download from python example, the result image with my postprocess code, seems not good.

![maskPrinted](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/865803/b0803e2f-8a02-4262-8a2f-0657de7862ea)

**Comment by omerwer** [comment]
Hi @dongxuanlb,
These are the result I get with the images provided by us in the repo:
![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/58146682/cec6eff4-7ab7-4a63-8d13-1cae0be3bf6b)

![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/58146682/6b67fcd6-e66d-4ba1-8267-1bda40f3a145)

Please notice that the results from the semseg model might not be that great as it's a relatively small segment-all model with relatively low accuracy. This example is mainly for showing Hailo's chip capabilities.

Regards,

**Comment by dongxuanlb** [comment]
I'll try running it with my implementation and see if it's similar. many thanks again.
