### ISSUE TITLE
Inquiring About Further Examples for YOLOv8-seg Inference on Windows

### ISSUE THREAD

**Issue by pcycccccc** [hailo-ai/Hailo-Application-Code-Examples#257]
Hello, I have successfully run inference with a custom dataset using the YOLOv8 model on Windows, and the results were impressive. I am interested in further exploring how to perform inference with the YOLOv8-seg model on Windows, but I am unsure about how to obtain the segmentation branch results. The examples provided for Windows are still too limited. Will there be new code examples provided for this in the future?

**Comment by omerwer** [comment]
Hi @pcycccccc,
Currently, we do not have an open task for creating a Windows example for yolov8-seg. You are welcome to open a request for it using the Hailo website and we will review it.
In the meantime, you can try to take the Linux yolov8-seg example and try to compile it for Windows using the CMakeLists.txt from the yolov5 Windows example. I assume that it won't compile right out of the box, but it will give you a good base to start with.

Regards,
