### ISSUE TITLE
package `loguru` not included in `requirements.txt`

### ISSUE THREAD

**Issue by talcs** [hailo-ai/Hailo-Application-Code-Examples#269]
Hello,

The Python object detection example seems to have been widely refactored recently.
While trying to run the example `object_detection.py` script from the new repository's version, even after calling `pip install requirements.txt`, I got an error for the package/module `loguru` not being installed. I installed it manually using pip and it solved the problem.

You may want to add it to the object detection's requirements file.

Thanks.

**Comment by omerwer** [comment]
Hi @talcs,
Thank you for pointing it out. The loguru option is now added to the requirements.txt file.

Regards,
