### ISSUE TITLE
Allowing a BHWC array as batch input in `runtime/python/utils.py`

### ISSUE THREAD

**Issue by talcs** [hailo-ai/Hailo-Application-Code-Examples#273]
## Edit

I'm sorry, I misunderstood the code. I thought that the support of arrays/tuples as inputs was there to facilitate batches, while it appears to be facilitating architectures that have multiple inputs for a single forward run (like stereo). I still haven't understood how to inference image batches though.

--------------------------

Hello,

The object detection Python example relies on the file `runtime/python/utils.py`.

When the input is a NumPy array of a single batch, i.e., `1xHxWxC`, everything works fine.

However, when sending a batch using a  `BxHxWxC` NumPy array, it crashes, as it assumes that a single NumPy array has to be a single image and that a batch must be provided as a list/tuple:

```
if isinstance(input_data, dict):
    # Input data is already a dictionary
    input_dict = {k: v.copy() for k, v in input_data.items()}
elif isinstance(input_data, (list, tuple)):
    # Input data is a list or tuple
    for i, layer_info in enumerate(self.input_vstream_info):
        input_dict[layer_info.name] = np.expand_dims(input_data[i].copy(), axis=0)
else:
    # Input data is a single array
    input_dict[self.input_vstream_info[0].name] = np.expand_dims(input_data.copy(), axis=0)
```

I think the code should be changed such that `elif isinstance(input_data, (list, tuple)):` will become `elif isinstance(input_data, (list, tuple)) or (len(input_data.shape) > 3 and input_data.shape[0] > 1):`.  It will take care of cases where the a single NumPy array contains an entire batch of inputs.

**Comment by nina-vilela** [comment]
Hi @talcs,

We have fixed the code.
Thank you for reporting the issue!
