### ISSUE TITLE
Hailo - 15 SBC Eror: Segmentation fault

### ISSUE THREAD

**Issue by Coder9234** [hailo-ai/Hailo-Application-Code-Examples#294]
I was trying to test the cascaded_network_dynamic_osd.cpp file which is present in Hailo-Application-Examples directory but I am getting segmentation error. I tried using the HEF file from the model zoo but it is returning HEF file length does not match error. The version of both HailoRT and Hailo 15 compiler is same which is 4.17.0.  Please guide me further in order to solve the problem.
![mode-zoo-error](https://github.com/user-attachments/assets/312b7ec4-0bdb-4c57-b7f1-702b5a2b6da9)
![gdb](https://github.com/user-attachments/assets/4fe1c359-241e-484d-9a33-627dee723769)

**Comment by omerwer** [comment]
Hi @Coder9234,
This specific code was not maintained and is initially broken. We currently removed it from the repo and are working to fix it. Thank you for pointing this out and sorry for the inconvenience. 

Regards,
