### ISSUE TITLE
memory Leak Problem yolov5_yolov7_detection_cpp

### ISSUE THREAD

**Issue by MyraBaba** [hailo-ai/Hailo-Application-Code-Examples#7]
Hi @omerwer 

with a high definition videos (5160x1440) the code is crashing due to increasing the memory to 10+Gb and the kernel killing it. 

what would  be the causing this memory leak ? 

Best

**Comment by omerwer** [comment]
Hi @MyraBaba 
I can't be sure, but it might be that the HailoRT itself uses large buffers as as you can see in the code, there are no malloc instructions and no "new" instantiations.
It might be that you run out of RAM memory when you ran it.

Regards,

**Comment by MyraBaba** [comment]
Hi,

https://drive.google.com/file/d/15PoLCWxrjITV5SP4TZMjyKPamO0vH6V_/view?usp=share_link 

This is the video that we tested and the memory increasing very fast and killed itself. Increasing to 24+ GB and stopped.

You can test with above video…


Best

**Comment by omerwer** [comment]
@MyraBaba 
Try adding
`frames[i].release();`
at the end of the  `for (auto &detection : detections)` detection loop in the post_processing_all function.
I checked with your video on my machine after adding this line and the inference finished successfully and I didn't see any additional memory usage.

Regards,

**Comment by MyraBaba** [comment]
Isn’t the memory usage increased when running ? 

Best

**Comment by MyraBaba** [comment]
Hi,

After added   

> frames[i].release();
> 
> 
Its fixed.

Thanks
