### ISSUE TITLE
when i add 25 networks to hailo , the error as follow

### ISSUE THREAD

**Issue by lswgh** [hailo-ai/Hailo-Application-Code-Examples#78]
![捕获](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/58289826/e0cb3784-020b-4967-b64e-725b0d25ae21)

**Comment by omerwer** [comment]
Hi @lswgh 
What example did you run? and what exactly do you mean by "added 25 networks to hailo"?

Regards,

**Comment by lswgh** [comment]
> Hi @lswgh What example did you run? and what exactly do you mean by "added 25 networks to hailo"?
> 
> Regards,
My code reference examples from  MultiNetworkPipeline-Scheduler

**Comment by omerwer** [comment]
Hi @lswgh 
We have no such example in this git repo from what I see. Do you mean the RE-ID example?

Regards,

**Comment by lswgh** [comment]
> Hi @lswgh We have no such example in this git repo from what I see. Do you mean the RE-ID example?
> 
> Regards,

can you give me you email , i will send you the code i debug .

**Comment by omerwer** [comment]
@lswgh 
Sure, you can contact me at omerw@hailo.ai

**Comment by lswgh** [comment]
> omerw@hailo.ai

Sorry for replying you so late. My code has been sent to your email
