### ISSUE TITLE
Not work if class number is not 80

### ISSUE THREAD

**Issue by Numb-66** [hailo-ai/Hailo-Application-Code-Examples#98]
Retraining a yolov8 model with 20 classes, and it doesn't work in the example.
Since I'm not familiar xTensor we did a work around to solve this issue.  Not sure if this change is correct but at least it works for us.
Below diff for your info.
yolov8_cpp/x86_64/yolov8_postprocess.cpp
(-)        auto output_scores = xt::view(dequantized_output_s, xt::all(), xt::all(), xt::all());
(+)       auto output_scores = xt::view(dequantized_output_s, xt::all(), xt::all(), xt::range(0, NUM_CLASSES));

**Comment by Numb-66** [comment]
Changed NUM_CLASSES  is not enough to run this example with the non-80-classes network.
Attached a 20-classes yolov8 network for test (cut out 21th-80th classes of coco128, still work for bus.jpg prediction).
[yolov8m_20classes.zip](https://github.com/hailo-ai/Hailo-Application-Code-Examples/files/12011689/yolov8m_20classes.zip)

**Comment by omerwer** [comment]
@Numb-66 
I looked at your model the output tensors data type is uint8.
If you look at the README.md of the yolo8 example, you'll see that there are notes there that the example is meant for a model with output data type of 16bit, but it can be easily changed to support an 8bit output model as well. 
I checked with your model after changing the NUM_CLASSES to 20 and changing all the relevant data structures (in lines mentioned in the README.md) from uint16_t to uint8_t, and I was able to run inference successfully.

Please change the code to support 8bit outputs and try running inference again.

**Comment by Numb-66** [comment]
After clean the output director build and rebuild the example, now the network work like a charm. Thanks
