### ISSUE TITLE
Not able to run my own yolov7 inference model

### ISSUE THREAD

**Issue by HY1998CN** [hailo-ai/Hailo-Application-Code-Examples#99]
Dear team,

thank you for your time. I downloaded the hefs by `get_hefs_and_video.sh`, it works fine.

Then I tried with my own inference model, here is the error message:

```
[HailoRT] [warning] HEF was compiled assuming clock rate of 400 MHz, while the device clock rate is 200 MHz. FPS calculations might not be accurate.
[HailoRT] [warning] HEF was compiled assuming clock rate of 400 MHz, while the device clock rate is 200 MHz. FPS calculations might not be accurate.
-I-----------------------------------------------
-I-  Network  Name                                     
-I-----------------------------------------------
-I-  IN:  yolov7_tiny/input_layer1
-I-----------------------------------------------
-I-  OUT: yolov7_tiny/conv43
-I-  OUT: yolov7_tiny/conv51
-I-  OUT: yolov7_tiny/conv58
-I-----------------------------------------------

-I- Started write thread: yolov7_tiny/input_layer1 (640, 640, 3)
-I- Started read thread: yolov7_tiny/conv43 (80, 80, 21)
-I- Started read thread: yolov7_tiny/conv58 (20, 20, 21)
-I- Started read thread: yolov7_tiny/conv51 (40, 40, 21)

-I- Starting postprocessing

Config file doesn't exist, using default parameters
[HailoRT] [error] CHECK failed - yolov7_tiny/input_layer1 (H2D) failed with status=HAILO_TIMEOUT(4), timeout=10000ms
[HailoRT] [error] CHECK_SUCCESS_AS_EXPECTED failed with status=HAILO_TIMEOUT(4)
[HailoRT] [error] CHECK_EXPECTED failed with status=HAILO_TIMEOUT(4)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_TIMEOUT(4) - HwWriteElement15_yolov7_tiny/input_layer1 (H2D) failed with status=HAILO_TIMEOUT(4)
[HailoRT] [error] CHECK failed - yolov7_tiny/input_layer1 (H2D) failed with status=HAILO_TIMEOUT(4), timeout=10000ms
[HailoRT] [error] CHECK_SUCCESS_AS_EXPECTED failed with status=HAILO_TIMEOUT(4)
[HailoRT] [error] CHECK_EXPECTED failed with status=HAILO_TIMEOUT(4)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_TIMEOUT(4) - HwWriteElement15_yolov7_tiny/input_layer1 (H2D) failed with status=HAILO_TIMEOUT(4)
```

To be more specific, there is no detection while running.

Do you have any idea how to address this issue?

Best,
Hui

**Comment by omerwer** [comment]
Hi @HY1998CN,
You are using a model that is trained on 21 classes, while by default the example is considering a 80 classes model.
To change that, run the inference example with the flag --classes 21.

Regards,

**Comment by omerwer** [comment]
Hi @HY1998CN ,

The example is using the default yolov7.json in the folder that have 80 classes, and is loaded when you run the run command with the flag 'arch=yolov7'. Please try running the example with the arch flag.
 
In addition, the yolov7.json to that is used have 80 classes. To have the correct detection labels, please change the json file to the correct classes your model was trained on.

Regards,

**Comment by HY1998CN** [comment]
Hi @omerwer ,

Thank you for your reply. I modified the `anchors` and `labels` in yolov7.json according to our model and loaded the config file while running. However, we still have this error message.

Best,
Hui

**Comment by omerwer** [comment]
Hi @HY1998CN 
Can you paste the HEF file of your model?
Plus, can you check if your model is successfully inferenced with out Python yolo inference code here:
https://github.com/hailo-ai/Hailo-Application-Code-Examples/tree/main/python/yolo_general_inference

Regards,

**Comment by HY1998CN** [comment]
Hi @omerwer ,

Thank you for your reply. We have successfully compiled the hef model with previous version of Hailo Software Suite. https://github.com/hailo-ai/hailo_model_zoo/issues/60#issue-1807547366

Best,
Hui
